// vue3/src/components/common/BaseButton.vue
<script setup>
defineProps({
  type: {
    type: String,
    default: "button",
    validator: (value) => ["button", "submit", "reset"].includes(value),
  },
  classes: {
    type: String,
    default: "",
  },
  disabled: {
    type: Boolean,
    default: false,
  },
  click: {
    type: Function,
    default: () => {},
  },
});
</script>

<template>
  <button
    :type="type"
    :disabled="disabled"
    @click="click"
    :class="[
      'bg-teal-600 text-sm active:bg-teal-700 hover:bg-teal-500 px-4 py-2 rounded-md text-white transition-all',
      classes,
    ]"
  >
    <slot />
  </button>
</template>

// html-css-advance/src/components/bases/BaseButton.jsx
import React from "react";
import PropTypes from "prop-types";

const BaseButton = ({ text, onClick, className }) => {
  return (
    <button
      onClick={onClick}
      className={`lg:px-6 sm:px-4 py-3 bg-pink-500 hover:bg-pink-600 active:opacity-75 transition-all text-white rounded-md ${className} md:px-4`}
    >
      {text}
    </button>
  );
};

BaseButton.propTypes = {
  text: PropTypes.string,
  onClick: PropTypes.func,
  className: PropTypes.string,
};

export default BaseButton;
